# Use the latest LTS version of Node.js
FROM node:lts-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and pnpm-lock.yaml files to the working directory
COPY pnpm-lock.yaml package.json ./

# Install PNPM globally and install dependencies
RUN npm install -g pnpm && pnpm install

# Copy the rest of the application files to the working directory
COPY . .

# Expose port 5000
EXPOSE 5000

# Start the application
CMD ["pnpm", "start", "--host", "0.0.0.0"]
