name: Docker Image CI (For ghcr.io) . . .

on:
   pull_request:
      branches:
         - 'dev'
   push:
      branches:
         - 'dev'
   workflow_dispatch:

jobs:
   build:
      runs-on: ubuntu-latest
      env:
         GITHUB_USERNAME: ${{ github.actor }}
      steps:
         - name: Checkout Repository
           uses: actions/checkout@v2

         - name: Convert User Name to lowercase
           run: |
              echo "GITHUB_USERNAME=${GITHUB_USERNAME,,}" >>${GITHUB_ENV}

         - name: Login to Github Container Registry (GHR)
           uses: docker/login-action@v3
           with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

         - name: Build and Push - Frontend Image
           uses: docker/build-push-action@v5
           with:
              context: ./frontend
              file: ./frontend/Dockerfile.dev
              push: true
              tags: ghcr.io/${{ env.GITHUB_USERNAME }}/online-class-management-system:dev

         - name: Build and Push - Backend Image
           uses: docker/build-push-action@v5
           with:
              context: ./backend
              file: ./backend/Dockerfile.dev
              push: true
              tags: ghcr.io/${{ env.GITHUB_USERNAME }}/online-class-management-system-backend:dev
