name: Docker Image CI (For ghcr.io)

on:
   push:
      branches:
         - 'dev'
         - 'main'
         - 'feature/*'
   workflow_dispatch:

env:
   REGISTRY: ghcr.io
   GITHUB_USERNAME: ${{ github.actor }}
   IMAGE_NAME: online-class-management-system
   DIR_NAME: frontend
   DOCKERFILE: Dockerfile
   DOCKER_IMAGE: ShanelkaPramuditha/online-class-management-system:latest

jobs:
   docker-image-build:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write
      steps:
         - name: Checkout Repository
           uses: actions/checkout@v3

         - name: Convert User Name to lowercase
           run: |
              echo "GITHUB_USERNAME=${GITHUB_USERNAME,,}" >>${GITHUB_ENV}

         - name: Login to Github Container Registry (GHR)
           uses: docker/login-action@v3
           with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

         - name: Extract metadata (tags, labels) for Docker
           id: meta
           uses: docker/metadata-action@v3
           with:
              images: ${{ env.REGISTRY }}/${{ env.GITHUB_USERNAME }}/${{ env.IMAGE_NAME }}
              flavor: |
                 latest=false
                 suffix=-${{ github.event_name }}

         - name: Determine Branch Name
           run: echo "BRANCH_NAME=$(echo ${{ github.ref }} | awk -F'/' '{print $NF}')" >> $GITHUB_ENV

         - name: Build and Push - Frontend Image
           uses: docker/build-push-action@v2
           with:
              context: ./frontend
              file: ./frontend/Dockerfile.dev
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              #   platforms: linux/amd64,linux/arm64

         - name: Build and Push - Backend Image
           uses: docker/build-push-action@v2
           with:
              context: ./backend
              file: ./backend/Dockerfile.dev
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              platforms: linux/amd64,linux/arm64
