name: Docker Image CI (For ghcr.io)

on:
   push:
      branches:
         - 'dev'
         - 'main'
         - 'feature/*'
      tags:
         - 'v*.*.*'
   workflow_dispatch:

env:
   REGISTRY: ghcr.io
   GITHUB_USERNAME: ${{ github.actor }}
   IMAGE_NAME: ${{ github.repository }}
   DIR_NAME: front
   DOCKER_IMAGE: shanelka/classmanage:main

jobs:
   docker-image-build:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write

      steps:
         - name: Checkout Repository
           uses: actions/checkout@v3

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v1

         - name: Login to Github Container Registry (GHR)
           uses: docker/login-action@v1
           with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

         - name: Convert User Name to lowercase
           run: |
              echo "GITHUB_USERNAME=${GITHUB_USERNAME,,}" >>${GITHUB_ENV}

         - name: Determine Branch Name
           run: echo "BRANCH_NAME=$(echo ${{ github.ref }} | awk -F'/' '{print $NF}')" >> $GITHUB_ENV

         - name: Extract metadata (tags, labels) for Docker
           id: meta
           uses: docker/metadata-action@v3
           with:
              images: ${{ env.REGISTRY }}/${{ env.GITHUB_USERNAME }}/${{ env.IMAGE_NAME }}
              flavor: |
                 latest=false
                 suffix=-${{ github.event_name }}

         - name: Build and push Docker image (Frontend)
           uses: docker/build-push-action@v2
           with:
              context: ./frontend
              file: ./frontend/Dockerfile.dev
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
              platforms: linux/amd64,linux/arm64
